export type ImageCredit = {
  file: string;
  title: string;
  creator: string;
  license: string;
  licenseUrl: string;
  source: string;
};

export const imageCredits: ImageCredit[] = [
  {
    file: "contract-pen",
    title: "Legal Contract & Signature - Cool Tones",
    creator: "Visual Content",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/143601516@N03/27571322193",
  },
  {
    file: "clipboard-contract",
    title: "Office Work",
    creator: "Ch%E2u%20Th%F4ng%20Phan",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://stocksnap.io/photo/office-work-UP9J4EZYNJ",
  },
  {
    file: "deal-table",
    title: "Two Person Shaking Each Others Hands - Credit to http://homedust.com/",
    creator: "Homedust",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/159630537@N08/28861151058",
  },
  {
    file: "agreement",
    title: "handshake sealing the deal",
    creator: "franchiseopportunitiesphotos",
    license: "BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    source: "https://www.flickr.com/photos/150276478@N03/34679366495",
  },
  {
    file: "handshake-suits",
    title: "Handshake - 2 men",
    creator: "flazingo_photos",
    license: "BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    source: "https://www.flickr.com/photos/124247024@N07/13903385550",
  },
  {
    file: "crane",
    title: "Construction Site Crane",
    creator: "Unknown",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://www.rawpixel.com/image/5969704/construction-site-crane",
  },
  {
    file: "site",
    title: "2007.08 - 'View over the metro construction site' underground with the rolling work platform including building crane overhead; on the North side of Amsterdam; Dutch city photo + geotag, Fons Heijnsbroek, The Netherlands",
    creator: "Amsterdam free photos & pictures of the Dutch city",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://www.flickr.com/photos/104736837@N03/10574456115",
  },
  {
    file: "containers",
    title: "Stacks shipping containers Port Barcelona",
    creator: "Unknown",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://www.rawpixel.com/image/3305642/free-photo-image-shipping-cargo-transportation-containers",
  },
  {
    file: "port",
    title: "Shipping containers port",
    creator: "Unknown",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://www.rawpixel.com/image/6026504/photo-image-public-domain-free",
  },
  {
    file: "servers",
    title: "Army unveils RDECOM laboratory to improve agile acquisition process",
    creator: "U.S. Army Combat Capabilities Development Command",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/34402227@N03/7447867664",
  },
  {
    file: "pylons",
    title: "High Voltage Line",
    creator: "ThomasKohler",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/28077296@N02/5787970432",
  },
  {
    file: "retail",
    title: "Kmart - Fairfax, VA",
    creator: "Robert Stinnett",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/93732749@N00/3835562004",
  },
  {
    file: "towers",
    title: "Buildings in Downtown LA",
    creator: "ricardodiaz11",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/41652235@N00/604551936",
  },
  {
    file: "boardroom",
    title: "007 EXPLAINS HIS THEORY OF THE SECRET THREAD ..",
    creator: "mrbill78636",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/88611824@N00/3973554998",
  },
  {
    file: "gavel-books",
    title: "Court Gavel - Judge's Gavel - Courtroom",
    creator: "weiss_paarz_photos",
    license: "BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    source: "https://www.flickr.com/photos/141290938@N03/26682691294",
  },
  {
    file: "gavel-scales",
    title: "484563651",
    creator: "verkeorg",
    license: "BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    source: "https://www.flickr.com/photos/68471686@N07/25102323896",
  },
  {
    file: "factory",
    title: "Tesla Motors Assembly Line",
    creator: "jurvetson",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/44124348109@N01/6858583426",
  },
  {
    file: "calculator-ledger",
    title: "Calculator and Pen with Ledger",
    creator: "seniorplanning",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/126131780@N08/14877276186",
  },
  {
    file: "calculator-figures",
    title: "Balancing The Account",
    creator: "kenteegardin",
    license: "BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    source: "https://www.flickr.com/photos/26373139@N08/5912231439",
  },
  {
    file: "analysis-desk",
    title: "Business plan - Credit to https://www.semtrio.com/",
    creator: "Semtrio",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/163837264@N07/43291332124",
  },
  {
    file: "charts-paper",
    title: "The Fruits of Religion 17",
    creator: "andymangold",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/30116130@N03/3488742295",
  },
  {
    file: "spreadsheet-glasses",
    title: "Numbers And Finance",
    creator: "kenteegardin",
    license: "BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    source: "https://www.flickr.com/photos/26373139@N08/5537894072",
  },
  {
    file: "mixing-desk",
    title: "Project 365 #44: 130209 A Bit of a Mix Up",
    creator: "comedy_nose",
    license: "PDM 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    source: "https://www.flickr.com/photos/23408922@N07/3276362047",
  },
  {
    file: "trucks",
    title: "Delivery truck, logistics freight delivery",
    creator: "Unknown",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://www.rawpixel.com/image/6030836/photo-image-public-domain-free-delivery",
  },
  {
    file: "exchange",
    title: "Placeholder",
    creator: "ehnmark",
    license: "BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    source: "https://www.flickr.com/photos/48600108001@N01/3970640849",
  },
  {
    file: "coins-chart",
    title: "Graph With Stacks Of Coins",
    creator: "kenteegardin",
    license: "BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    source: "https://www.flickr.com/photos/26373139@N08/6093690339",
  },
];
